--drop user LITTLEECO cascade;
----
--CREATE USER LITTLEECO IDENTIFIED BY LITTLEECO;
--GRANT CONNECT, RESOURCE TO LITTLEECO;
--
--grant unlimited tablespace to LITTLEECO;
--MEMBER테이블 CATEGORY_NO 컬럼 삭제 12.13+
--게시판 테이블들 comment추가, COUNT 디폴트값 0, 공지사항 데이터 추가, 게시판 좋아요 테이블 status 추가
--여기서부터 LITTEECO 계정으로
--12/21 세춘 : FOREIGN KEY(FOLDER_NO) REFERENCES MYPAGE(FOLDER_NO) ON DELETE CASCADE 제약조건 추가
-- 맨 아래 데모데이터 안들어가는거 신경 안쓰셔도 됩니다
-- 01/07 세춘 MEMBER 테이블 탈퇴사유 컬럼 추가 , 스크랩쪽 제약조건 수정 스크랩 일자 추가
-- ECO_LIKE 테이블 컬럼명 수정
-- 게시판 쪽 THUM_IMG 데이터타입 수정
-- searchEco content컬럼 clob 수정
DROP SEQUENCE SEQ_CNO;
DROP SEQUENCE SEQ_MANO;
DROP SEQUENCE SEQ_MZNO;
DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_BNO;
DROP SEQUENCE SEQ_ANO;
DROP SEQUENCE SEQ_BANO;
DROP SEQUENCE SEQ_SRNO;
DROP SEQUENCE SEQ_MYNO;
DROP SEQUENCE SEQ_EBNO;
DROP SEQUENCE SEQ_RBNO;
DROP SEQUENCE SEQ_NFNO;
DROP TABLE BRAND_CATEGORY;
DROP TABLE MEMBER_CATEGORY;
DROP TABLE MOIZA_CATEGORY;
DROP TABLE ATTACHMENT;
DROP TABLE MOIZA_MEMBER;
DROP TABLE MOIZA_ATTACHMENT;
DROP TABLE SEARCH;
DROP TABLE INTEREST_BOARD;
DROP TABLE MYPAGE;
DROP TABLE BOARD_ATTACHMENT;
DROP TABLE ECO_LIKE;
DROP TABLE RECYCLE_BOARD;
DROP TABLE SEARCHECO_BOARD;
DROP TABLE NOTICE_FAQ_BOARD;
DROP TABLE MOIZA;
DROP TABLE CATEGORY;
DROP TABLE BRAND;
DROP TABLE MEMBER;
--MEMBER 테이블
CREATE TABLE MEMBER(
    MEMBER_NO NUMBER CONSTRAINT FK_MEMBER_NO PRIMARY KEY,
    MEMBER_ID VARCHAR2(30) CONSTRAINT MID_NN NOT NULL CONSTRAINT UID_UNIQUE UNIQUE,
    MEMBER_PWD VARCHAR2(300) CONSTRAINT MPWD_NN NOT NULL,
    MEMBER_NAME VARCHAR2(15) CONSTRAINT MNAME_NN NOT NULL,
    NICKNAME VARCHAR2(100) NOT NULL,
    BIRTH VARCHAR2(8),
    GENDER CHAR(1),
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(13),
    CREATE_DATE DATE DEFAULT SYSDATE,
    WITHDRAWAL_REASON   VARCHAR2(1000 BYTE) ,
    STATUS CHAR(1) DEFAULT 'Y' CONSTRAINT MEM_STATUS CHECK (STATUS IN('Y', 'N'))
);
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID  IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD  IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME  IS '이름';
COMMENT ON COLUMN MEMBER.NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.BIRTH IS '생일';
COMMENT ON COLUMN MEMBER.GENDER  IS '성별(M/F)';
COMMENT ON COLUMN MEMBER.EMAIL  IS '이메일';
COMMENT ON COLUMN MEMBER.PHONE  IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.CREATE_DATE  IS '가입일';
COMMENT ON COLUMN MEMBER.STATUS  IS '상태값(Y/N)';
COMMENT ON COLUMN MEMBER.WITHDRAWAL_REASON IS '탈퇴 사유';
CREATE SEQUENCE SEQ_MNO
NOCACHE;

--CATEGORY TABLE
CREATE TABLE CATEGORY(
CATEGORY_NO NUMBER PRIMARY KEY,
CATEGORY_TYPE_NAME VARCHAR2(300) NOT NULL,
CATEGORY_NAME VARCHAR2(45) NOT NULL
);
CREATE SEQUENCE SEQ_CNO
NOCACHE;
COMMENT ON COLUMN CATEGORY.CATEGORY_NO  IS '카테고리 번호';
COMMENT ON COLUMN CATEGORY.CATEGORY_TYPE_NAME  IS '카테고리 타입 이름';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME  IS '카테고리 이름';
SELECT * FROM CATEGORY;
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TYPE_NAME, CATEGORY_NAME ) VALUES (SEQ_CNO.NEXTVAL, '주제별' ,'지속 가능 제품');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TYPE_NAME, CATEGORY_NAME ) VALUES (SEQ_CNO.NEXTVAL, '주제별' ,'사회적 기업');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TYPE_NAME, CATEGORY_NAME ) VALUES (SEQ_CNO.NEXTVAL, '주제별' ,'제로웨이스트 및 친환경 제품');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TYPE_NAME, CATEGORY_NAME ) VALUES (SEQ_CNO.NEXTVAL, '주제별' ,'친환경 교육 및 커뮤니티');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TYPE_NAME, CATEGORY_NAME ) VALUES (SEQ_CNO.NEXTVAL, '구매목적별' ,'유기농 식품');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TYPE_NAME, CATEGORY_NAME ) VALUES (SEQ_CNO.NEXTVAL, '구매목적별' ,'주방 용품');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TYPE_NAME, CATEGORY_NAME ) VALUES (SEQ_CNO.NEXTVAL, '구매목적별' ,'욕실 용품');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TYPE_NAME, CATEGORY_NAME ) VALUES (SEQ_CNO.NEXTVAL, '구매목적별' ,'생활 용품');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TYPE_NAME, CATEGORY_NAME ) VALUES (SEQ_CNO.NEXTVAL, '구매목적별' ,'패션');
CREATE TABLE MEMBER_CATEGORY(
MEMBER_NO NUMBER NOT NULL,
CATEGORY_NO NUMBER NOT NULL,
FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT MEMBER_LIKES_PK PRIMARY KEY(MEMBER_NO,CATEGORY_NO)
);
COMMENT ON COLUMN MEMBER_CATEGORY.CATEGORY_NO  IS '카테고리 번호';
COMMENT ON COLUMN MEMBER_CATEGORY.MEMBER_NO  IS '회원 번호';
--BRAND TABLE
CREATE TABLE BRAND(
    BRAND_NO NUMBER  CONSTRAINT FK_BRAND_NO PRIMARY KEY,
    BRAND_NAME VARCHAR2(300) NOT NULL,
    BRAND_URL VARCHAR2(300) NOT NULL,
    BRAND_INFO VARCHAR2(4000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT 'Y' CONSTRAINT BRAND_STATUS CHECK (STATUS IN('Y', 'N'))
);
SELECT * FROM 
BRAND;
CREATE SEQUENCE SEQ_BNO
NOCACHE;
COMMENT ON COLUMN BRAND.BRAND_NO  IS '브랜드 번호';
COMMENT ON COLUMN BRAND.BRAND_NAME  IS '브랜드 이름';
COMMENT ON COLUMN BRAND.BRAND_URL  IS '브랜드 URL';
COMMENT ON COLUMN BRAND.BRAND_INFO IS '브랜드 정보';
COMMENT ON COLUMN BRAND.CREATE_DATE  IS '생성일자';
COMMENT ON COLUMN BRAND.STATUS  IS '상태값(Y/N)';

--BRAND CATEGORY TABLE
CREATE TABLE BRAND_CATEGORY(
BRAND_NO NUMBER NOT NULL,
CATEGORY_NO NUMBER NOT NULL,
FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO),
    FOREIGN KEY (BRAND_NO) REFERENCES BRAND(BRAND_NO),
    CONSTRAINT BRAND_LIKES_PK PRIMARY KEY(BRAND_NO,CATEGORY_NO)
);
COMMENT ON COLUMN BRAND_CATEGORY.CATEGORY_NO  IS '카테고리 번호';
COMMENT ON COLUMN BRAND_CATEGORY.BRAND_NO  IS '브랜드 번호';
CREATE TABLE ATTACHMENT(
FILE_NO NUMBER CONSTRAINT FK_BRAND_FILE_NO PRIMARY KEY,
BRAND_NO NUMBER NOT NULL,
ORIGIN_NAME VARCHAR2(255),
CHANGE_NAME VARCHAR2(255),
FILE_PATH VARCHAR2(1000),
CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
FILE_LEVEL NUMBER,
STATUS  CHAR(1) DEFAULT 'Y' CONSTRAINT BRAND_ATTACHMENT_STATUS CHECK (STATUS IN('Y', 'N')),
FOREIGN KEY (BRAND_NO) REFERENCES BRAND(BRAND_NO)
);
CREATE SEQUENCE SEQ_ANO
NOCACHE;
COMMENT ON COLUMN ATTACHMENT.FILE_NO  IS '파일 번호';
COMMENT ON COLUMN ATTACHMENT.BRAND_NO  IS '브랜드 번호';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME  IS '파일원본명';
COMMENT ON COLUMN ATTACHMENT.CHANGE_NAME  IS '파일 수정명';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH  IS '저장 폴더 경로';
COMMENT ON COLUMN ATTACHMENT.CREATE_DATE  IS '작성일';
COMMENT ON COLUMN ATTACHMENT.FILE_LEVEL  IS '파일레벨';
COMMENT ON COLUMN ATTACHMENT.STATUS  IS '상태값(Y/N)';
--MOIZA TABLE
CREATE TABLE MOIZA(
MOIZA_NO NUMBER PRIMARY KEY,
MOIZA_NAME VARCHAR2(300) NOT NULL,
MOIZA_TITLE VARCHAR2(300) NOT NULL,
MOIZA_GOAL VARCHAR2(2000) NOT NULL,
MOIZA_MISSION  VARCHAR2(2000) NOT NULL,
MOIZA_INFO VARCHAR2(4000) NOT NULL,
CREATE_DATE DATE DEFAULT SYSDATE,
STATUS CHAR(1) DEFAULT 'Y' CONSTRAINT MOIZA_STATUS CHECK (STATUS IN('Y', 'N'))
);
CREATE SEQUENCE SEQ_MZNO
NOCACHE;
COMMENT ON COLUMN MOIZA.MOIZA_NO  IS '단체 번호';
COMMENT ON COLUMN MOIZA.MOIZA_NAME  IS '단체 이름';
COMMENT ON COLUMN MOIZA.MOIZA_TITLE  IS '단체 한줄소개';
COMMENT ON COLUMN MOIZA.MOIZA_GOAL IS '단체 목표';
COMMENT ON COLUMN MOIZA.MOIZA_MISSION IS '단체 미션';
COMMENT ON COLUMN MOIZA.MOIZA_INFO IS '단체 정보';
COMMENT ON COLUMN MOIZA.CREATE_DATE  IS '생성일자';
COMMENT ON COLUMN MOIZA.STATUS  IS '상태값(Y/N)';
SELECT * FROM MOIZA;

CREATE TABLE MOIZA_MEMBER(
MOIZA_NO NUMBER,
MEMBER_NO NUMBER,
MEMBER_LEVEL NUMBER NOT NULL,
APPROVAL_STATUS NUMBER NOT NULL,
CREATE_DATE DATE DEFAULT SYSDATE,
DELETE_DATE DATE,
FOREIGN KEY (MOIZA_NO) REFERENCES MOIZA(MOIZA_NO),
FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);
COMMENT ON COLUMN MOIZA_MEMBER.MEMBER_NO  IS '회원 번호';
COMMENT ON COLUMN MOIZA_MEMBER.MOIZA_NO  IS '단체 번호';
COMMENT ON COLUMN MOIZA_MEMBER.MEMBER_LEVEL  IS '회원 레벨';
COMMENT ON COLUMN MOIZA_MEMBER.APPROVAL_STATUS  IS '승인상태';
COMMENT ON COLUMN MOIZA_MEMBER.CREATE_DATE  IS '가입일';
COMMENT ON COLUMN MOIZA_MEMBER.DELETE_DATE  IS '탈퇴일';
CREATE TABLE  MOIZA_CATEGORY(
 MOIZA_NO NUMBER NOT NULL,
CATEGORY_NO NUMBER NOT NULL,
FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO),
    FOREIGN KEY ( MOIZA_NO) REFERENCES  MOIZA( MOIZA_NO),
    CONSTRAINT  MOIZA_C_PK PRIMARY KEY( MOIZA_NO,CATEGORY_NO)
);
COMMENT ON COLUMN MOIZA_CATEGORY.CATEGORY_NO  IS '카테고리 번호';
COMMENT ON COLUMN MOIZA_CATEGORY.MOIZA_NO  IS '단체 번호';
CREATE TABLE MOIZA_ATTACHMENT(
FILE_NO NUMBER CONSTRAINT FK_MOIZA_FILE_NO PRIMARY KEY,
MOIZA_NO NUMBER NOT NULL,
ORIGIN_NAME VARCHAR2(255),
CHANGE_NAME VARCHAR2(255),
FILE_PATH VARCHAR2(1000),
CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
FILE_LEVEL NUMBER,
STATUS  CHAR(1) DEFAULT 'Y' CONSTRAINT MOIZA_ATTACHMENT_STATUS CHECK (STATUS IN('Y', 'N')),
FOREIGN KEY (MOIZA_NO) REFERENCES MOIZA(MOIZA_NO)
);
CREATE SEQUENCE SEQ_MANO
NOCACHE;
COMMENT ON COLUMN MOIZA_ATTACHMENT.FILE_NO  IS '파일 번호';
COMMENT ON COLUMN MOIZA_ATTACHMENT.MOIZA_NO  IS '단체 번호';
COMMENT ON COLUMN MOIZA_ATTACHMENT.ORIGIN_NAME  IS '파일원본명';
COMMENT ON COLUMN MOIZA_ATTACHMENT.CHANGE_NAME  IS '파일 수정명';
COMMENT ON COLUMN MOIZA_ATTACHMENT.FILE_PATH  IS '저장 폴더 경로';
COMMENT ON COLUMN MOIZA_ATTACHMENT.CREATE_DATE  IS '작성일';
COMMENT ON COLUMN MOIZA_ATTACHMENT.FILE_LEVEL  IS '파일레벨';
COMMENT ON COLUMN MOIZA_ATTACHMENT.STATUS  IS '상태값(Y/N)';
-------------------서치에코 게시판------------------------
CREATE TABLE SEARCHECO_BOARD (
    ECO_BOARD_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER,
    BRAND_NO NUMBER,
    THUM_IMG VARCHAR2(1000),
    ECO_BOARD_TITLE VARCHAR2(1000),
    ECO_BOARD_CONTENT CLOB,
    COUNT NUMBER DEFAULT 0,
    LIKE_COUNT NUMBER DEFAULT 0,
    CREATE_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT 'Y',
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (BRAND_NO) REFERENCES BRAND(BRAND_NO)
);
CREATE SEQUENCE SEQ_EBNO
NOCACHE;
COMMENT ON COLUMN SEARCHECO_BOARD.ECO_BOARD_NO IS '서치에코 글번호';
COMMENT ON COLUMN SEARCHECO_BOARD.MEMBER_NO IS '작성자';
COMMENT ON COLUMN SEARCHECO_BOARD.BRAND_NO IS '브랜드 번호';
COMMENT ON COLUMN SEARCHECO_BOARD.THUM_IMG IS '썸네일';
COMMENT ON COLUMN SEARCHECO_BOARD.ECO_BOARD_TITLE IS '제목';
COMMENT ON COLUMN SEARCHECO_BOARD.ECO_BOARD_CONTENT IS '내용';
COMMENT ON COLUMN SEARCHECO_BOARD.COUNT IS '조회수';
COMMENT ON COLUMN SEARCHECO_BOARD.LIKE_COUNT IS '좋아요 수';
COMMENT ON COLUMN SEARCHECO_BOARD.CREATE_DATE IS '생성일';
COMMENT ON COLUMN SEARCHECO_BOARD.MODIFY_DATE IS '수정일';
COMMENT ON COLUMN SEARCHECO_BOARD.STATUS IS '사용여부';
---------게시판 좋아요 테이블 ------------
CREATE TABLE ECO_LIKE (
    MEMBER_NO NUMBER,
    ECO_BOARD_NO NUMBER,
    STATUS CHAR(1) DEFAULT 'Y',
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (ECO_BOARD_NO) REFERENCES SEARCHECO_BOARD (ECO_BOARD_NO)
);
COMMENT ON COLUMN ECO_LIKE.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN ECO_LIKE.ECO_BOARD_NO IS '서치에코 게시글 번호';
COMMENT ON COLUMN ECO_LIKE.STATUS IS '사용여부';
--------------------- HOW TO RECYCLE ------------------
CREATE TABLE RECYCLE_BOARD (
    BOARD_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER,
    RECY_BOARD_TITLE VARCHAR2(300),
    RECY_BOARD_CONTENT CLOB,
    THUM_IMG VARCHAR2(1000),
    COUNT NUMBER DEFAULT 0,
    CREATE_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT 'Y',
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);
CREATE SEQUENCE SEQ_RBNO
NOCACHE;
COMMENT ON COLUMN RECYCLE_BOARD.BOARD_NO IS '리사이클 글번호';
COMMENT ON COLUMN RECYCLE_BOARD.MEMBER_NO IS '작성자';
COMMENT ON COLUMN RECYCLE_BOARD.RECY_BOARD_TITLE IS '글제목';
COMMENT ON COLUMN RECYCLE_BOARD.RECY_BOARD_CONTENT IS '내용';
COMMENT ON COLUMN RECYCLE_BOARD.THUM_IMG IS '썸네일';
COMMENT ON COLUMN RECYCLE_BOARD.COUNT IS '조회수';
COMMENT ON COLUMN RECYCLE_BOARD.CREATE_DATE IS '생성일';
COMMENT ON COLUMN RECYCLE_BOARD.MODIFY_DATE IS '수정일';
COMMENT ON COLUMN RECYCLE_BOARD.STATUS IS '사용여부';
-----------------게시판 첨부파일--------------------
CREATE TABLE BOARD_ATTACHMENT (
    BO_FILE_NO NUMBER PRIMARY KEY,
    BOARD_NO NUMBER,
    BOARD_TYPE NUMBER,
    BO_FILE_TYPE NUMBER,
    BO_ORIGIN_NAME VARCHAR2(4000),
    BO_CHANGE_NAME VARCHAR2(4000),
    FILE_PATH VARCHAR2(1000),
    FILE_LEVEL NUMBER,
    CREATE_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT 'Y'
);
CREATE SEQUENCE SEQ_BANO
NOCACHE;
COMMENT ON COLUMN BOARD_ATTACHMENT.BO_FILE_NO IS '게시판 첨부파일 번호';
COMMENT ON COLUMN BOARD_ATTACHMENT.BOARD_NO IS '게시판 글번호';
COMMENT ON COLUMN BOARD_ATTACHMENT.BOARD_TYPE IS '게시판 구분';
COMMENT ON COLUMN BOARD_ATTACHMENT.BO_FILE_TYPE IS '게시판 첨부파일 타입';
COMMENT ON COLUMN BOARD_ATTACHMENT.BO_ORIGIN_NAME IS '첨부파일 기존';
COMMENT ON COLUMN BOARD_ATTACHMENT.BO_CHANGE_NAME IS '첨부파일 변경';
COMMENT ON COLUMN BOARD_ATTACHMENT.FILE_PATH IS '파일 경로';
COMMENT ON COLUMN BOARD_ATTACHMENT.FILE_LEVEL IS '파일 레벨';
COMMENT ON COLUMN BOARD_ATTACHMENT.CREATE_DATE IS '생성일자';
COMMENT ON COLUMN BOARD_ATTACHMENT.STATUS IS '사용여부';
---------공지사항 FAQ 게시판 --------------
CREATE TABLE NOTICE_FAQ_BOARD(
   BOARD_NO NUMBER PRIMARY KEY,
   MEMBER_NO NUMBER ,
   BOARD_CATEGORY NUMBER,
   BOARD_TITLE VARCHAR2(300),
   BOARD_CONTENT VARCHAR2(4000),
   COUNT NUMBER DEFAULT 0,
   CREATE_DATE DATE DEFAULT SYSDATE,
   MODIFY_DATE DATE DEFAULT SYSDATE,
   STATUS CHAR(1) DEFAULT 'Y' CONSTRAINT NOTICE_FAQ_STATUS CHECK (STATUS IN('Y', 'N')),
   FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);
CREATE SEQUENCE SEQ_NFNO
NOCACHE;
COMMENT ON COLUMN NOTICE_FAQ_BOARD.BOARD_NO IS '공지사항게시판번호';
COMMENT ON COLUMN NOTICE_FAQ_BOARD.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN NOTICE_FAQ_BOARD.BOARD_CATEGORY IS '공지사항FAQ카테고리';
COMMENT ON COLUMN NOTICE_FAQ_BOARD.BOARD_TITLE IS '공지게시판제목';
COMMENT ON COLUMN NOTICE_FAQ_BOARD.BOARD_CONTENT IS '공지게시판내용';
COMMENT ON COLUMN NOTICE_FAQ_BOARD.COUNT IS '공지사항조회수';
COMMENT ON COLUMN NOTICE_FAQ_BOARD.CREATE_DATE IS '게시글작성시간';
COMMENT ON COLUMN NOTICE_FAQ_BOARD.MODIFY_DATE IS '게시글수정시간';
COMMENT ON COLUMN NOTICE_FAQ_BOARD.STATUS IS '상태값';
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다TEST','공지사항내용입니다TEST',0,SYSDATE,NULL,'Y');
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다','공지사항내용입니다',0,SYSDATE,NULL,'Y');
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다1','공지사항내용입니다1',0,SYSDATE,NULL,'Y');
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다2','공지사항내용입니다2',0,SYSDATE,NULL,'Y');
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다3','공지사항내용입니다3',0,SYSDATE,NULL,'Y');
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다4','공지사항내용입니다4',0,SYSDATE,NULL,'Y');
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다5','공지사항내용입니다5',0,SYSDATE,NULL,'Y');
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다6','공지사항내용입니다6',0,SYSDATE,NULL,'Y');
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다7','공지사항내용입니다7',0,SYSDATE,NULL,'Y');
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다8','공지사항내용입니다8',0,SYSDATE,NULL,'Y');
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다9','공지사항내용입니다9',0,SYSDATE,NULL,'Y');
INSERT INTO NOTICE_FAQ_BOARD VALUES(SEQ_NFNO.NEXTVAL,1,1,'공지사항입니다0','공지사항내용입니다0',0,SYSDATE,NULL,'Y');
--제일 밑줄에 넣어주세요
--------------------------------
----------- 인기검색어 -----------
--------------------------------
CREATE TABLE SEARCH(
    KEYWORD_NO  NUMBER  PRIMARY KEY,
    KEYWORD VARCHAR(200)    NOT NULL,
    SEARCH_COUNT   NUMBER  NULL,
    UPDATE_DATE  DATE DEFAULT SYSDATE   
);
CREATE SEQUENCE SEQ_SRNO
NOCACHE;
COMMENT ON COLUMN SEARCH.KEYWORD_NO IS '검색어 식별자'; 
COMMENT ON COLUMN SEARCH.KEYWORD IS '검색어';
COMMENT ON COLUMN SEARCH.SEARCH_COUNT IS '검색된 횟수';
COMMENT ON COLUMN SEARCH.UPDATE_DATE IS '검색된 날짜';
INSERT INTO SEARCH VALUES(SEQ_SRNO.NEXTVAL,'검색해봄2',5,DEFAULT);
INSERT INTO SEARCH VALUES(SEQ_SRNO.NEXTVAL,'검색해봄3',8,DEFAULT);
INSERT INTO SEARCH VALUES(SEQ_SRNO.NEXTVAL,'검색해봄4',3,DEFAULT);
INSERT INTO SEARCH VALUES(SEQ_SRNO.NEXTVAL,'검색해봄5',4,DEFAULT);
INSERT INTO SEARCH VALUES(SEQ_SRNO.NEXTVAL,'검색해봄5',2,DEFAULT);
--------------------------------------
----------- 마이페이지 관련 ------------
--------------------------------------
CREATE TABLE MYPAGE (
    FOLDER_NO   NUMBER  PRIMARY KEY,
    MEMBER_NO   NUMBER  NOT NULL,
    FOLDER_NAME VARCHAR2(40) NOT NULL,
    PARENT_FOLDER_NO    NUMBER  ,
    CREATE_DATE DATE    DEFAULT SYSDATE ,
    
    FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);
COMMENT ON COLUMN MYPAGE.FOLDER_NO IS '폴더 번호';
COMMENT ON COLUMN MYPAGE.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN MYPAGE.FOLDER_NAME IS '폴더 이름';
COMMENT ON COLUMN MYPAGE.PARENT_FOLDER_NO IS '상위 폴더 번호';
COMMENT ON COLUMN MYPAGE.CREATE_DATE IS '폴더 생성 날짜';
CREATE SEQUENCE SEQ_MYNO
NOCACHE;
INSERT INTO MYPAGE VALUES(SEQ_MYNO.NEXTVAL,1,'폴더1',NULL,DEFAULT);
INSERT INTO MYPAGE VALUES(SEQ_MYNO.NEXTVAL,1,'폴더2',NULL,DEFAULT);
INSERT INTO MYPAGE VALUES(SEQ_MYNO.NEXTVAL,1,'폴더3',NULL,DEFAULT);
INSERT INTO MYPAGE VALUES(SEQ_MYNO.NEXTVAL,1,'폴더4',NULL,DEFAULT);
-------------------------------
------------ 스크랩 ------------
-------------------------------
CREATE TABLE INTEREST_BOARD (
    MEMBER_NO   NUMBER  ,
    FOLDER_NO   NUMBER  ,
    BOARD_NO    NUMBER  ,
    ECO_BOARD_NO NUMBER ,
    MOIZA_NO NUMBER ,
    SCRAP_DATE DATE DEFAULT SYSDATE,
    
    FOREIGN KEY(BOARD_NO) REFERENCES RECYCLE_BOARD(BOARD_NO),
    FOREIGN KEY(ECO_BOARD_NO) REFERENCES SEARCHECO_BOARD(ECO_BOARD_NO),
    FOREIGN KEY(MOIZA_NO) REFERENCES MOIZA(MOIZA_NO),
    FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY(FOLDER_NO) REFERENCES MYPAGE(FOLDER_NO) ON DELETE CASCADE
);
COMMENT ON COLUMN INTEREST_BOARD.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN INTEREST_BOARD.FOLDER_NO IS '폴더 번호';
COMMENT ON COLUMN INTEREST_BOARD.BOARD_NO IS '리사이클 게시판 번호';
COMMENT ON COLUMN INTEREST_BOARD.ECO_BOARD_NO IS '브랜드 게시판 번호';
COMMENT ON COLUMN INTEREST_BOARD.MOIZA_NO IS '모집 게시판 번호';
COMMENT ON COLUMN INTEREST_BOARD.SCRAP_DATE IS '스크랩 한 일자';
INSERT INTO INTEREST_BOARD VALUES(1,1,1,NULL,NULL,DEFAULT);
INSERT INTO INTEREST_BOARD VALUES(1,1,2,NULL,NULL,DEFAULT);
INSERT INTO INTEREST_BOARD VALUES(1,1,3,NULL,NULL,DEFAULT);
INSERT INTO INTEREST_BOARD VALUES(1,1,NULL,1,NULL,DEFAULT);
INSERT INTO INTEREST_BOARD VALUES(2,2,NULL,NULL,1,DEFAULT);
------------------------------
----하원은지 sql 변경 사항---
------------------------------
---- 1. 새로운 CLOB 열 추가
--ALTER TABLE SEARCHECO_BOARD
--ADD (ECO_BOARD_CONTENT CLOB);
---- 2. 기존 BOARD_CONTENT에서 NEW_BOARD_CONTENT로 데이터 복사
--UPDATE SEARCHECO_BOARD
--SET NEW_ECO_BOARD_CONTENT = ECO_BOARD_CONTENT;
---- 3. 기존 BOARD_CONTENT 열 삭제
--ALTER TABLE SEARCHECO_BOARD
--DROP COLUMN ECO_BOARD_CONTENT;
commit;